### ISSUE TITLE
Add support for SRI like in Webpack-Html-Plugin

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/webpack-flush-chunks#10]
It would be nice when the plugin would be able to use the `integrity` information added to assets by the SRI plugin: https://www.npmjs.com/package/webpack-subresource-integrity.

This section might be helpful for implementation:
https://www.npmjs.com/package/webpack-subresource-integrity#without-htmlwebpackplugin

With this is place it would be safe to push all these bundles onto a CDN as the browser checks whether the SRI checksums are matching and the correct files are being delivered.

**Comment by faceyspacey** [comment]
That doesn't seem too hard. I don't use it. It's probably best in userland. It seems if you just have an array of `chunkNames` (which I can return in the final return as a minor change), you can use just the returned `stylesheets` and `scripts` and construct the `<script />` and `<link />` strings yourself by using each chunk name to get the `integrity` value from `stats.compilation.assets[mainAssetName].integrity`. 

I.e. to create something like this:

```js
<link
     rel="stylesheet"
     href="<%= htmlWebpackPlugin.files.css[index] %>"
     integrity="<%= htmlWebpackPlugin.files.cssIntegrity[index] %>"
     crossorigin="<%= webpackConfig.output.crossOriginLoading %>"
  />
```

And of course the `crossOriginLoading` it seems you will already know. 

If you're using Webpack "magic comments" and [React Universal Component](https://github.com/faceyspacey/react-universal-component) you will in fact already have the chunk names for all dynamic chunks, and you should know the chunk names for named entry points. 

Perhaps that solves your problem for now. You can use the [Low-level API](https://github.com/faceyspacey/webpack-flush-chunks#low-level-api-flushfiles) to achieve this.

**Comment by faceyspacey** [comment]
I'm just gonna close this cuz I'm cleaning house and likely won't be able to prioritize it.
