### ISSUE TITLE
Inject other scripts between bootstrap and dynamic chunks.

### ISSUE THREAD

**Issue by aga5tya** [faceyspacey/webpack-flush-chunks#16]
@faceyspacey First off, Kudos!!! Really like your SSR based approaches.

Coming to the point, i have my codebase that has a vendor dll lib that produces a packed bundle on development mode. The flushChunks doesn't give me this lib name since it's only referenced in webpack bundling. 

If i try to inject this before the bootstrap chunk i get checksum mismatch in the browser. Any help on how do i get around with this ? I also tried adding it in the `before` array that flushChunk accepts, but doesn't seem to recognize it. 

Edit:
@faceyspacey: Irrespective of the order when dll script is included, i still get the checksum mismatch issue. That's probably because the dll has the react put into it. This problem won't be in production but i'm just curious as to why i get checksum mismatch with chunks in place.

**Comment by chrisblossom** [comment]
I am using the DLL plugin without issue with this plugin.

[chrisblossom/react-universal-starter/src/server.js#L71-L73](https://github.com/chrisblossom/react-universal-starter/blob/6f065e1626029008c096a65d734310be77086ba9/src/server.js#L71-L73)

Do you have an example repo I can look at? Is it possible you are having the same issue found here: https://github.com/faceyspacey/react-universal-component/issues/10#issuecomment-312402406

**Comment by faceyspacey** [comment]
@aga5tya glad ur likin the goods.

...im gonna need more info. but here's ur checklist so hopefully that doesnt need to happen :):

-log `flushChunkNames()` and `flushModuleIds()` to make sure ur getting anything
-if ur using `flushChunkNames()` make sure ur giving ur components a `chunkName` prop (which as @chrisblossom pointed out is singular, which was incorrect in one place in the docs).
-make sure ur using a magic comment too
-if ur not going the chunk name route, make sure u have hashed and named module ids setup for both the client and the server
-if u have a babel server, make sure ur providing a `path` option
-if u have a webpack server, and ur using externals, make sure u follow the externals documentation so our components know it's running in Webpack
-study the webpack configuration docs in this repo relentlessly until u have everything nailed.


If that doesn't solve it, a repro is the only way we can help.

What I've found is the only thing that's not working is super fancy Webpack plugins. So before the repro, reduce the # of plugins to the bare minimum until u find the culprit. See what im saying. If ur following all directions correctly and ur not using some crazy plugin concoction, it will work. *SO, I look forward to hearing that it's working or exactly which plugin (and which options you used) broke it? 🚀 *

**Comment by aga5tya** [comment]
@chrisblossom @faceyspacey 
Thank you guys,, it was because my server webpack node_externals regex was going awry. Fixing that and the changing/removing plugins order to be similar to that of Chris's boilerplate did the trick. 🎉 

P.S.
@chrisblossom boilerplate has some good techniques that people could refer to, Good work with that. @faceyspacey just a suggestion, would be good to add a note for reference boilerplates on readme for beginners.

**Comment by chrisblossom** [comment]
@aga5tya Thanks! If you have any questions why I did something a certain way or suggestions please open an issue on my starter.
