### ISSUE TITLE
[question] Missing/wrong chunks with CommonChunksPlugin and dual-import

### ISSUE THREAD

**Issue by Craga89** [faceyspacey/webpack-flush-chunks#21]
My configuration makes extensive use of the `CommonsChunkPlugin` to bundle common dependencies into `async` chunks. Unfortunately, this causes issues the `babel-plugin-dual-import` and this plugin, as the CSS files the modules within the commons chunk refer to are no longer in the location they assume, but within a combined commons chunk.

For example, if I have `src/moduleA` and `src/moduleB`, the `importCSS` call injected via `babel-plugin-dual-import` assumes that each of their stylesheets are in `src/moduleA.css` and `src/moduleB.css` respectively. However, when these are combined into an async chunk using `CommonsChunkPlugin`, say named `common`, both stylesheets now actually reside at `common.css`.

`webpack-flush-chunks` gives the "correct" output of these chunks when looking at the CSS Hash, but obviously since `babel-plugin-dual-import` has no knowledge of the output chunks, the stylesheets it refers to are not in the hash e.g.

```js
var cssHashWithoutCommonsChunkPlugin = {
   "src/moduleA": "output/moduleA.css",
   "src/moduleB": "output/moduleB.css"
}

var cssHashWithCommonsChunkPlugin = {
   "common": "output/common.css" // <- moduleA and moduleB have no entries now :(
}
```

Is there a recommended approach to solving this? The only way I can think of doing it is to inject an entry into the CSS hash for `src/moduleA` and `src/moduleB`, which points to the bundled `common.css`. This will however result in *multiple <link> tags being injected that point to the same stylesheet* which obviously isn't ideal.

**Comment by faceyspacey** [comment]
This is a very interesting (and should be common) use case. I can't think right now how to support it. 

But here's a userland solution:

Rewrite the hash manually on the server to be:

```js
var cssHashWithoutCommonsChunkPlugin = {
   "src/moduleA": "output/common.css" ,
   "src/moduleB": "output/common.css" 
}
```

I guess that's exactly what you said at the end. The dual import plugin could be PRed to not inject anything if a stylesheet with the given `href` already exists, right around here:

https://github.com/faceyspacey/babel-plugin-dual-import/blob/master/importCss.js#L27

Also I'm not sure if you saw and if it applies to you, but there's now also a `babel-plugin-universal-import`:

https://medium.com/faceyspacey/announcing-react-universal-component-2-0-babel-plugin-universal-import-5702d59ec1f4

It adds additional features to apply to React Universal Component. If you're using RUC, you probably want to upgrade to the 2.0 and use that plugin. Both babel plugins share the same css injection code.

**Comment by faceyspacey** [comment]
the one caveat with this approach is that it's not DRY, as it's not resilient when it comes to changing the location of modules in your file system. You could make it such, and to do so you'd have to use the chunkName trimming here:

https://github.com/faceyspacey/babel-plugin-dual-import/blob/master/index.js#L8

It's probably not the biggest deal, but I thought I'd point it out.

**Comment by Craga89** [comment]
Yes I thought that might be the case for an interim solution. Not ideal! Especially because my file names use output hashes so they're not static :(. I wonder if there's a way to process the `stats` using some naming convention for async chunks and generate these entries after `flushChunks` is called? The information must be in there somewhere!

As for the universal component, I'm not using React in this specific use case so opted for the `dual-import` as is detailed on the repo guide. Is this still valid or should I upgrade?

**Comment by faceyspacey** [comment]
No, it's valid. It's fine. 

the assets are here:

```js
stats.assetsByChunkName
```

The implementation of this function should help you:
https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L192

the key on the above object should be `common`. Unfortunately for autodll it cant get in there because the plugin cant add to stats. But maybe optimizeChunks can.

**Comment by Craga89** [comment]
For those of you having this issue, I've temporarily worked around it by forcefully excluding any module that has CSS extracted via the `extract-css-chunks-webpack-plugin`. You can do this by adding the following logic into your `minChunks` property of your `CommonsChunkPlugin`:

```js

const moduleHasExtractedCss = (module) => {
	if (!module.dependencies) {
		return false;
	}

	return module.dependencies.some((dep) => {
		if (!dep.module) {
			return false;
		}

		return /extract-css-chunks-webpack-plugin/.test(dep.module.request);
	});
};
```
```js
new CommonsChunkPlugin({
   // ...other options here
   minChunks(module, count) {
      if (moduleHasExtractedCss(module)) {
         return false;
      }

      // ...other logic here
   }
```

**Comment by faceyspacey** [comment]
solid!

**Comment by faceyspacey** [comment]
closin this out for now, as I'm not sure what we can do beside your manual strategy.
