### ISSUE TITLE
flushChunks - cssHash only providing 1 of 2 CSS chunks consumed by any JS chunk

### ISSUE THREAD

**Issue by willmcpo** [faceyspacey/webpack-flush-chunks#25]
Hi @faceyspacey 

We are using UniversalComponent with webpack-flush-chunks. 

Because our project is a mix of SASS and PostCSS, we have 2 instances of ExtractCssChunks - one for SASS transpilation, and one for PostCSS transpilation. In the end, for many components, webpack creates 2 CSS files with the formats `[name]-post-[chunkhash:6].css & [name]-[chunkhash:6].css`.

When I check `windows.__CSS_CHUNKS_`, I can only see css files from the PostCSS transpilation.

So the outcome is, when a page rendered with `UniversalComponent` is loaded asynchronously on the client, only 1 of the 2 CSS files are loaded.

However, if I load the same page synchronously, both 2 of the 2 CSS files are loaded, and I can see these being loaded in the network tab in Devtools (as well as these filenames being provided in the `stylesheets` value returned from `flushChunks`).

Can you suggest a way for this to be remedied? Perhaps each key of the CSS hash needs to support an array of CSS files ?

**Comment by faceyspacey** [comment]
That one will take some changes to do. If u figure out how to generate a hash of arrays for CSS hash I'll do the babel plugin :)

Just look in the code in this package and u will find it in no time.

**Comment by faceyspacey** [comment]
It's at the bottom of this file:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/createApiWithCss.js

The only challenge is it's basically a breaking change to anyone accessing the CSS hash directly which some might. We could keep string values when there aren't multiple style sheets but then that makes implementation code unnecessarily more complex. So I'm inclined to just do a major version bump and skip to always having array values.

From there the babel plugin has to be able to fetch multiple stylesheet if found in the hash.

**Comment by faceyspacey** [comment]
If u want this done quickly here's the code that fetches the CSS as I won't have time for a week or two:

https://github.com/faceyspacey/babel-plugin-universal-import/blob/master/importCss.js

So the getHref function on the bottom looks in the hash. It will now return an array. So what needs to be done is multiple style sheets are embedded if found, and the promise only resolves once all are added (or if one fails it rejects).

**Comment by willmcpo** [comment]
Thanks for the suggestions. I may or may not get time to do it before you do, would definitely like to help out. Will keep you posted on how I go.

**Comment by zackljackson** [comment]
Update everything, no longer a problem
