### ISSUE TITLE
Dependencies of react

### ISSUE THREAD

**Issue by BernardoS** [faceyspacey/webpack-flush-chunks#26]
I was trying to use this amazing tool with [require-universal-module](https://github.com/faceyspacey/require-universal-module) in an no react environment. but apparently this library is react dependant.

```log
ERROR in (webpack)-flush-chunks/dist/createApiWithCss.js
    Module not found: Error: Can't resolve 'react' in 'C:\Users\bernardosunderhus\Desktop\pextra\node_modules\webpack-flush-chunks\dist'
     @ (webpack)-flush-chunks/dist/createApiWithCss.js 8:13-29
     @ (webpack)-flush-chunks/dist/flushChunks.js
     @ ./src/node/index.js
```

Is there any plans to make this work without this dependency?

**Comment by faceyspacey** [comment]
just import `node_modules/dist/flushChunks.js` directly, and u will get everything except all the pre-created strings and react components. U may have to do the following line manually:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/createApiWithCss.js#L138

:)

good luck. let me know how it goes and what ur using it for.

**Comment by faceyspacey** [comment]
crap, im an asshole, that wont work. i thought it was something else i had done. ..cuz yea it will import the createApiWithCss file just the same.

**Comment by faceyspacey** [comment]
basically `flushFiles` will do what you want in a lower level way:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L85

the problem it its in the same file. 

basically, a PR would have to be made to re-arrange things so you can do the import like I initially suggested.

Another way if ur using webpack is just to alias `react` to nothing, and just use `flushFiles`, which won't in fact call `createApiWithCss`.

**Comment by BernardoS** [comment]
challenge accepted! I'll make a PR of something
