### ISSUE TITLE
Unable to find component in folder

### ISSUE THREAD

**Issue by jmn69** [faceyspacey/webpack-flush-chunks#30]
Hi,

I forked your redux first router demo repository and made my experimental app from it.
So i dont copy the config files because they are the same from your repository.

When i try to import a component with Universal like this : 

`const UniversalComponent = universal(
    props => import('./questions/${props.component}')
);` 

This is the tree directory :

    |-- UniversalComponent.js
    |-- questions 
        |-- CheckSingle.jsx
        |-- Other components..

I've got the following error : 
`[FLUSH CHUNKS]: Unable to find questions/CheckSingle in Webpack chunks. Please check usage of Babel plugin.`

I checked the stats.json and all the files in questions folder appear to be there.
If i used universal to load pages just like your demo it works nicely. But when i want to create a folder and import a component in it, this time it doesnt work.

I think there is something i dont understand.

What i am missing ?

**Comment by faceyspacey** [comment]
try only using the `.js` extension. no `.jsx`. 

Also log `stats.assetsByChunkName` to see what you have. There likely isn't one called `questions/CheckSingle`. Find out what's there.

**Comment by jmn69** [comment]
I switched extension to .js but still the same error.
I log assetsByChunkName and i think i understand why flush-chunks is unable to find the component : 

`{ 
'questions-CheckSingle': [ 'questions-CheckSingle.js', 'questions-CheckSingle.js.map' ],
...
}`

It's because of the prefix 'questions-' right ?

**Comment by faceyspacey** [comment]
yes.

make sure in all places you import it exactly like this:

```js
import('./questions/${props.component}')
```

with the `questions` folder starting.  if looks like somewhere else you're doing `./${props.components}`. Maybe you have some temporary code you were trying. Webpack is picking one of the 2 to create the chunks.

**Comment by jmn69** [comment]
Yes i have this to load page
```javascript
export default universal(({ page }) => import(`./${page}`), {
  minDelay: 500,
  loading: loading,
  chunkName: props => props.page,
  error: () => <div className={notFound}>PAGE NOT FOUND - 404</div>
})
```

In one of those pages i want to load questions components so i used another universal component. I've got temporary code but i pushed them a minute ago so you can see it on my repository.

You can see the all project here : 
https://github.com/jmn69/project-survey

From what i'am understanding here, i must have only one universal import ? 
My only goal is to organize my components with some folder but i didnt succeed so far.

**Comment by faceyspacey** [comment]
np.

..yup. that's the problem. see here:
https://github.com/jmn69/project-survey/blob/5907dfe48921a50eb66f4367090d333c585f59ed/client/components/UniversalComponent.js#L19


u can have multiple. but it's about how u do it. in that component you're requiring from your main components folder. that means webpack will create chunks for every possible component in that folder, and any folders within it recursively. that will increase build time significantly. it also happens to mean webpack is being told twice to create chunks in the questions folder. so webpack will pick one of them.

move whatever u want in the components folder to another folder like the questions folder. it's the only and best way to do dynamic expressions. :)
