### ISSUE TITLE
Usage when writing an npm package

### ISSUE THREAD

**Issue by chapati23** [faceyspacey/webpack-flush-chunks#31]
We ran into a challenge last week that we couldn't solve with CSS Modules + webpack-flush-chunks. Maybe you have a recommendation here.

We have a core-ui repository with components we use in all of our apps like Button, TextInput, Logo etc.

We consume this repo in other apps as an npm module. Our goal is to be able to `import Button from 'core-ui/Button'` without any extra `import 'core-ui/Button/styles.css'` or a global `import 'core-ui/styles.css'`.

Haven't been able to get it working and had to resolve to using `styled-components`. We're not _too_ unhappy because we'll most likely also consume the core components in a future react-native app where `styled-components` might offer some benefits over CSS Modules but I was still wondering if there is a way to achieve the above with your setup?

**Comment by faceyspacey** [comment]
Try Emotion. They have an extract mode that uses a babel plugin to generate CSS from CSS-in-js components. And I think they have a React Native components as well.

**Comment by faceyspacey** [comment]
https://github.com/emotion-js/emotion/blob/master/docs/extract-static.md

Emotion is meant for this precise use case. I haven't tried it though, but I planned to and then to write an article about it. It's perfect for RUC. If it works, you should share your findings in an article.

**Comment by chapati23** [comment]
thanks man, i'll check it out this weekend

**Comment by oyeanuj** [comment]
@chapati23 Where did you end up with this?

**Comment by chapati23** [comment]
at using styled-components :)
works for us and didn't wanna prematurely refactor the whole styling to yet another stack before we actually run into performance problems.

**Comment by oyeanuj** [comment]
@chapati23 so SC and this library worked well for you together? If yes, what changes did you have to make, or how did you set it up?
