### ISSUE TITLE
get rid of [UNIVERSAL-IMPORT] no chunk,  {file} , found in "window.__CSS_CHUNKS__". If you are not serving CSS for this chunk, disregard this message.

### ISSUE THREAD

**Issue by GuillaumeCisco** [faceyspacey/webpack-flush-chunks#38]
Is there a way to get rid of 
`[UNIVERSAL-IMPORT] no chunk, {file} , found in "window.__CSS_CHUNKS__". If you are not serving CSS for this chunk, disregard this message.`

I use emotion (7.3.2) for dealing with css, so I usually write things like:
```javascript
import React from 'react';
import styled from 'react-emotion';

const Container = styled('div')`
    width: 800px;
    margin: 30px auto 0;
`;

const Content = styled('div')`
    margin-top: 70px;
    margin-left: 10px;
    font-size: 20px;
    justify-content: center; 
`;

const Home = props =>
    (<Container>
        <Content>
            <p>text</p>
        </Content>
    </Container>);

export default Home;
```

So I'm not doing things like `import './index.css'` at the top of the file. Consequently, `window.__CSS_CHUNKS__` does not have a css file retaled to its chunk.
I know I get only a warning, but it is a little annoying.
Can't we just disable it? Or provide an option for that?

**Comment by tguillemot** [comment]
https://github.com/faceyspacey/babel-plugin-universal-import#supressing-console-warnings solves the problem.

**Comment by GuillaumeCisco** [comment]
Thanks @tguillemot 
Closing this issue ;)
