### ISSUE TITLE
The `below` anchor link in README is broken

### ISSUE THREAD

**Issue by davidfurlong** [faceyspacey/webpack-flush-chunks#42]
In the last section of https://github.com/faceyspacey/webpack-flush-chunks#options-api

**Comment by faceyspacey** [comment]
it worked:

https://github.com/faceyspacey/webpack-flush-chunks#webpack-configuration

**Comment by davidfurlong** [comment]
Im sorry for the ambiguity, but the anchor that is broken is the one that links to:

https://github.com/faceyspacey/webpack-flush-chunks#3-css-instead-of-stylesheets

**Comment by faceyspacey** [comment]
ok
