### ISSUE TITLE
flushChunks(stats, { chunkNames })

### ISSUE THREAD

**Issue by valorloff** [faceyspacey/webpack-flush-chunks#47]
Hi!
Thanks for this an extremely useful packages!
Please, explain, what is `stats` and how to get them for: 
```
const { js, styles, cssHash } = flushChunks(stats, {
  chunkNames: flushChunkNames()
})
```
`chunkNames - ***array of chunks flushed from react-universal-component`
is it clients chunks? 
this should be the paths to the files, which is created by Universal Component with webpack-flush-chunks?

**Comment by faceyspacey** [comment]
Check this:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/docs/webpack-stats.md

`chunkNames` is the names of client chunks as flushed from `react-universal-component`. It's not exactly paths. It's the names given to chunks, using magic comments. Look into this article:

https://medium.com/faceyspacey/how-to-use-webpacks-new-magic-comment-feature-with-react-universal-component-ssr-a38fd3e296a

`babel-plugin-universal-import` automatically creates these names for you. And then your universal component is able to "flush" them when rendered. Then by cross-referencing them with info about your webpack client build (aka "stats"), we are able to generate the exact files to transport to the client. 

Hope that helps :)
