### ISSUE TITLE
Webpack/Babel Absolute Path is making FLUSH CHUNKS error

### ISSUE THREAD

**Issue by ZhengYuTay** [faceyspacey/webpack-flush-chunks#54]
When using absolute path resolve like 

```
import React from "react";
import universal from "react-universal-component";

const UniversalImport = universal(
  ({ page }) => {
    return import(`pages/${page}/${page}`);
  },
  {
    onLoad(module, info, props, context) {
      if (module.reducers) {
        context.store.injectReducers(module.reducers);
      }
    }
  }
);

export default UniversalImport;
```

Error:

> [FLUSH` CHUNKS]: Unable to find pages/Login-Login in Webpack chunks. Please check usage of Babel plugin.

This error occurs when using webpack resolve or babel-plugin-module-resolver.

**Comment by zackkirsh** [comment]
@ZhengYuTay This has been resolved, please update universal babel loader
