### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by davidfurlong** [faceyspacey/webpack-flush-chunks#55]
[Webpack 4 deprecates `CommonsChunkPlugin`](https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366)

We need an alternative to:

```js
new webpack.optimize.CommonsChunkPlugin({
    names: ['bootstrap'], 
    filename: '[name].js',
    minChunks: Infinity,
 })
```

and I have no idea how

**Comment by leebenson** [comment]
I just came across this issue after submitting [this SO question](https://stackoverflow.com/questions/49108737/webpack-4-getting-async-splitchunks-in-ssr-by-name-module-id).

If we can get this figured out, we'll have hit the motherload- uber-efficient Webpack 4 chunks via SplitChunksPlugin, plus true SSR for CSS + JS.

This is the magic we've been waiting for. Crazy more people aren't talking about/focused on this!

**Comment by faceyspacey** [comment]
We have had it for almost 8 months now :). It would appear React influencers don’t build apps anymore ;)

Quickest solution: Use webpack 3. 

I likely won’t find time to revisit this until the official suspense React async api is released and finalized, as that’s the most efficient path forward. 

That said it’s likely super easy—if u analyze the code here u will see that for flushing chunk names the shortest code path is used. This started out doing all this work based on module ids before webpack let you name your chunks. A lot of code can be deleted if you don’t need that path. In the next major version we probably will drop that. Check the source real quick and you may be surprised by how little it’s doing.

Also, all the info is easily accessible in stats.assetsByChunkName, and I assume it’s something similar still.

**Comment by faceyspacey** [comment]
Oh, the alternative to the original question is forget the bootstrap chunk. Instead in main.js assign a function called render or something similar to window.render and paste a script after all your chunks that simply calls it.

I probably won’t promote the bootstrap approach in any future major releases anyway as it causes too much confusion. The goal is simply to insure u don’t perform your first render until you have all the chunks.

**Comment by ermik** [comment]
### Every codebase is an idea...
And the documentation is usually a snapshot of that idea in time, but it could be more. It could capture the evolution of the idea and be a living document that builds a community around it by way of education and insight.

@faceyspacey thanks for the tips mate. Could we maybe work on moving these into README documentation as follows:
```markdown
## A note on Webpack 4
I likely won’t find time to revisit universal-related packages until 
the official suspense React async api is released and finalized, as 
it will mean significant changes and that’s the most efficient path forward. 
[...]

*Here's an example of how to work with Webpack 4....*
```javascript

// Todo:

```

**Comment by davidfurlong** [comment]
@ermik I like your approach but generally I find making a PR with the updated docs works better and takes no more time than suggesting them in an issue given how busy open source maintainers are

**Comment by ermik** [comment]
@davidfurlong I wouldn't know where to start, there would be a PR coming your way otherwise...

**Comment by leebenson** [comment]
FWIW, I got`.js` chunks working in Webpack 4 with react-loadable:

https://github.com/jamiebuilds/react-loadable/pull/111

**Comment by faceyspacey** [comment]
Yea but we don’t like React Loadable around these parts. Please use Universal instead. 

The original issue can be solved like I said by assigning your render function to window.render. So I’m not even sure what the problem is with webpack 4.

**Comment by faceyspacey** [comment]
Ps all my work started out as a PR to Loadable. It was ignored under false pretenses and then it’s creator did the core concept (universal rendering, which we pioneered) on his own months later. The dude ultimately is a bad seed. Just look at all his negative tweets and attitude on twitter. Don’t use his ware unless u have to. Ultimately his comments are closed and my ware is better and has far more capabilities. His is a little bit less webpack dependent. Anyway please come with a solution for Universal or ur banishes :) jk

**Comment by leebenson** [comment]
Fair enough. I personally don't get involved in politics- I'm here for the code, and grateful to anyone that spends their time sharing it for free. How someone acts outside of their git commits is frankly none of my business.

FWIW, I used react-loadable solely because I couldn't get the universal babel plugin to fire, whereas the other one seemed to work first time. It was probably just a config issue, but I went with what seemed to be working.

Now that I've had a little more direct experience with the shape of Webpack stats, I'll take a closer look at the Universal family of packages to see what I was doing wrong.

Thanks for your help.

**Comment by slavab89** [comment]
The easiest way to achieve the same behavior as the previous CommonsChunks - without additional splitting is to use:
```
optimization: {
  runtimeChunk: {
    name: 'bootstrap',
  },
  splitChunks: {
    chunks: 'initial', // <-- The key to this
    cacheGroups: {
      vendors: {
        test: /[\\/]node_modules[\\/]/,
        name: 'vendor',
      }
    },
  }
}
```

That worked for me at least. It would not create any additional chunks with `~` in their name etc.

**Comment by slavab89** [comment]
@faceyspacey i filed https://github.com/webpack/webpack/pull/7093. If and once merged it should be pretty easy to get all relevant chunks with webpack 4 and split/chunks

**Comment by davidfurlong** [comment]
That PR has been merged (although not yet released). Great job @slavab89

**Comment by medanat** [comment]
I believe the PR landed in https://github.com/webpack/webpack/releases/tag/v4.7.0

**Comment by tushar-singh** [comment]
Thanks @slavab89 

It's trivial with webpack 4.7.0

```javascript
const chunkNames = flushChunkNames();
const assets = {
    css: [],
    js: [],
};

chunkNames.forEach(chunkName => {
    const chunkAssets = clientStats.assetsByChunkName[chunkName];
    const js = chunkAssets.filter(filename => /.js$/.test(filename));
    const css = chunkAssets.filter(filename => /.css$/.test(filename));

    assets.js = assets.js.concat(js);
    assets.css = assets.css.concat(css);
});

console.log(assets); // { css: [ '1.css' ], js: [ 'chunk-routes/home.js' ] }
```

**Comment by slavab89** [comment]
Something similar yeah. You would have to use `namedChunkGroups` instead of `assetsByChunkName` as it was not changed. But other than that it should be the same 😄 
I am not sure if we can do a PR here for that as it requires webpack 4.7 so people with versions previous to that wont be able to use it.

**Comment by zackljackson** [comment]
@slavab89 Much appreciated!

Ill be PR code updates and ReadMe's for the community to follow. Overall its pretty easy and the main think is really just swapping out CSS loaders & updating the universal family.

**Comment by zackljackson** [comment]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/issues/60#issuecomment-392317314

**Comment by zackljackson** [comment]
Aggressive code splitting in Webpack 4 now supported. You should be able to use more complex optimization and chunking techniques.
https://github.com/faceyspacey/webpack-flush-chunks/pull/59

Now available via `@next` tag on NPM

**Comment by faceyspacey** [comment]
excellent work @zackljackson !!!!!
