### ISSUE TITLE
Breaks when using public path on the fly

### ISSUE THREAD

**Issue by franjohn21** [faceyspacey/webpack-flush-chunks#56]
If you are using a public path on the fly, then the `window.__CSS_CHUNKS__` maps to an incorrect URL as the `publicPath` does not exist in the `stats` object.

https://webpack.js.org/configuration/output/#output-publicpath
https://webpack.js.org/guides/public-path/#on-the-fly

I think the solution would be to detect if the stats file has the publicPath and if not then `babel-plugin-universal-import`'s [getHref function](https://github.com/faceyspacey/babel-plugin-universal-import/blob/cb4c5d3a240991af7445493f04908033df61c823/importCss.js#L86) should manually append the `__webpack_public_path__`. It would probably be even cleaner if webpack-flush-chunks never used the public path and left it entirely up to babel-plugin-universal-import to use the `__webpack_public_path__` but that would be a breaking change.

Happy to submit a PR if this generally makes sense.

**Comment by faceyspacey** [comment]
Hey, there, try setting `clientStats.publicPath` directly prior to calling `flushChunks`. That should handle it.
