### ISSUE TITLE
Ability to add a nonce-attribute to dynamically generated script tags to comply with strict Content-Security-Policy

### ISSUE THREAD

**Issue by chapati23** [faceyspacey/webpack-flush-chunks#57]
Hey :)
I'm doing a bit of security-hardening and wanted to switch to to a stricter content security policy (e.g. [Google's Strict CSP3 Example](https://csp.withgoogle.com/docs/strict-csp.html#example)).

This requires me adding nonce-attributes to all my script tags: `<script nonce="random-base64-string">`. I've managed to do this for _almost_ all script tags.

For the js chunks exposed by `webpack-flush-chunks` I hacked my way there:

```js
const myNonce = "someBase64String"
const { js: rawJs, styles, cssHash: rawCssHash } = flushChunks(
  clientStats,
  { chunkNames }
)
const js = rawJs.toString().replace('<script', `<script nonce="${myNonce}"`)
const cssHash = rawCssHash.toString().replace('<script', `<script nonce="${myNonce}"`)
```

However, I haven't managed to find a way to get these nonces into the dynamically loaded chunks.

According to the [webpack docs](https://webpack.js.org/guides/csp/) it's simply a matter of setting `__webpack_nonce__ = 'someBase64String';` at the top of my entry file (the `render.js` from the redux-first-router-demo repo). But no luck. No matter where I set the webpack-nonce, it doesn't pick it up.

Wasn't sure whether that's more of a `webpack-flush-chunks` or `babel-plugin-universal-import` (or something else entirely?) responsibility so I open this issue here.

Any advice?

**Comment by zackljackson** [comment]
Hey, you can also create your own script tags.

USe flush files if you need it. or just use the scripts and css directly to create your own tags

``` js
 const {publicPath, scripts, stylesheets} = flushedChunks;
    console.log('DYNAMIC CHUNK NAMES RENDERED', chunkNames); // eslint-disable-line  no-console
    console.log('SCRIPTS SERVED', scripts); // eslint-disable-line  no-console
    console.log('STYLESHEETS SERVED', stylesheets); // eslint-disable-line  no-console
    const assets = [...scripts, ...stylesheets].map((asset) =>
        `${publicPath}/${asset}` 
    );
```

**Comment by chapati23** [comment]
Hey @zackljackson, thanks for answering.

This gets me _almost_ to the goal. The problem is that the dynamic chunks don't receive a dynamic nonce-attribute. So with your approach i get to the point where everything renders fine on first load, however, clicking an internal link will fail in `bootstrap.js` (webpack) 

my hunch is that the whole server-rendering shenanigans somehow keep webpack to do it's job from reading the nonce from the `__webpack_nonce__ = "bla"` annotation inside my source code. because in a vanilla webpack, this works perfectly fine.

<img width="769" alt="screen_shot_2018-06-11_at_20_08_18" src="https://user-images.githubusercontent.com/117495/41249105-636d0380-6db3-11e8-86a1-a4f87283da12.png">

**Comment by zackljackson** [comment]
Okay man. I'm going to look at this a little later. 
Write me the client API you want for this and ill look at making it a reality <3 
 Whatcha want it to look like and ill investigate solutions. I understand why it cant be determined during the build because i assume the nonce you set is very dynamic & from an external source 
```js
flushChunks(
  clientStats,
  { chunkNames },
  myNonce
)
```

**Comment by chapati23** [comment]
You're correct, `nonce` needs to be generated server-side, otherwise bypassing the CSP becomes trivial when the nonce would be visible on client-side. The best litmus test would be to get `nonce`-support into https://github.com/faceyspacey/redux-first-router-demo as that combines server-rendering and aggressive code-splitting.

The API you're suggesting makes sense to me. Would call it just `nonce`, though. If you want it to be more specific you could also make it `csp-nonce`. Or, if you're a clean code aficionado: `content-security-policy-nonce` :)

Background info:
---

Why the `nonce` is useful:

>The nonce attribute enables you to “whitelist” certain inline `<script>` and `<style>` elements, while avoiding use of the CSP `'unsafe-inline'` directive (which would allow all inline script/style), so that you still retain the key CSP feature of disallowing inline script/style in general.
>
>So the `nonce` attribute is way of telling browsers that the inline contents of a particular script or style element were not injected into the document by some (malicious) third party, but were instead put into the document intentionally by whoever controls the server the document is served from.

Source: https://stackoverflow.com/a/42924000/619474

From MDN:

> A whitelist for specific inline scripts using a cryptographic nonce (number used once). The server must generate a unique nonce value each time it transmits a policy. It is critical to provide an unguessable nonce, as bypassing a resource’s policy is otherwise trivial. See [unsafe inline script](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_inline_script) for an example. Specifying nonce makes a modern browser ignore `'unsafe-inline'` which could still be set for older browsers without nonce support.

Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

**Comment by zackljackson** [comment]
Okay, I'm going to push this in a supplemental update. Are you able to update to webpack 4? this update is primarily for webpack 4 and includes some big refactors. 

I tried to support Webpack 3 as well but I've not tested the result

**Comment by faceyspacey** [comment]
I don't think this makes sense to be in our API. It can be achieved by using the low level arrays returned and manually build the scripts. As for the css hash script, use `cssHashRaw` and build that script. That's the whole purpose of also offering the low level API.

@zackljackson you have a lot on your plate right now. This is a distraction. 

@chapati23 if there's something I'm missing regarding why this cant be accomplished in userland, let us know in a PR. You know these tools very well, and this is our smallest package. Should be no big deal for you brotha. Sorry about this one brotha.

**Comment by chapati23** [comment]
The problem is not the chunks coming from the server in the first request, all files returned from `flushChunks` i'm of course able to insert my `nonce="base64yo"` into all scripts tags. The problem is the dynamic code-splitted chunk that gets loaded after navigating. Take `redux-first-router-demo` for example. First load is fine, problem is clicking a link, then the browser will throw when you use a strict CSP.

I don't know how to hook into the dynamically loaded chunk is what i'm saying. Just know that with vanilla webpack it works fine.

I get that everything's heavily in flux right now. So I guess I'll wait until `redux-first-router-demo` has been upgraded to `rudy` (or whatever the new version is called now 🙂) and submit a PR implementing a strict content security policy. Will probably make it easier to explain.

**Comment by Voronar** [comment]
Maybe `strict-dynamic` source expression helps (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic_2)

**Comment by protoEvangelion** [comment]
strict-dynamic won't work for dynamically added style tags though.
