### ISSUE TITLE
Stylesheets in reversed order

### ISSUE THREAD

**Issue by chrisblossom** [faceyspacey/webpack-flush-chunks#7]
CSS ordering is reversed as it would be if the files were not split into separate files.

```html
<head>
  <link rel='stylesheet' href='/static/0.css' />
  <link rel='stylesheet' href='/static/7.css' />
  <link rel='stylesheet' href='/static/main.css' />
</head> 
```

The CSS files should be reversed:

```html
<head>
  <link rel='stylesheet' href='/static/main.css' />
  <link rel='stylesheet' href='/static/7.css' />
  <link rel='stylesheet' href='/static/0.css' />
</head> 
```

**Comment by faceyspacey** [comment]
i noticed that too, but it also rests on the premise ur using css modules, which means they are *order-independent*. 

...perhaps there are users not using css modules. I honestly haven't even thought about whether stuff works without css modules. Why dont u make ur first PR that calls `arr.reverse()` somewhere. ...make sure u use `npm run cm` to make your commits as describe in the [contributing](https://github.com/faceyspacey/webpack-flush-chunks#contributing) section.

**Comment by faceyspacey** [comment]
https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/createApiWithCss.js#L36

**Comment by chrisblossom** [comment]
This was fixed with https://github.com/faceyspacey/webpack-flush-chunks/commit/2befa77c18492dd10a14201a34d795e99fbf3dfc right? I can close this?

**Comment by faceyspacey** [comment]
yup
